const mongoose = require("mongoose");
const dotenv   = require("dotenv");
const Product  = require("../models/Product");

dotenv.config();

const img = (name) => `images/${name}`;

const products = [

  // ── WOMEN — KURTAS (women_kurta1-15 + womens_kurta1-12) ──
  { name:"Floral Printed Cotton Kurta",     price:999,  originalPrice:1299, discount:23, category:"kurtas", gender:"women", images:[img("women_kurta1.webp"),  img("women_kurta2.jpg")],   sizes:["S","M","L","XL"],        colors:["Pink","White"],    stock:25, ratings:4.2, isFeatured:true  },
  { name:"Silk Festive Kurta",              price:1899, originalPrice:2499, discount:24, category:"kurtas", gender:"women", images:[img("women_kurta3.jpg"),   img("women_kurta4.jpg")],   sizes:["S","M","L","XL"],        colors:["Blue","Green"],    stock:20, ratings:4.4, isFeatured:true  },
  { name:"Printed Cotton Kurta",            price:1299, originalPrice:1799, discount:27, category:"kurtas", gender:"women", images:[img("women_kurta5.jpg"),   img("women_kurta6.jpg")],   sizes:["S","M","L","XL","XXL"],  colors:["Mustard","Teal"],  stock:18, ratings:4.5, isFeatured:false },
  { name:"Designer Silk Kurta",             price:2199, originalPrice:2999, discount:26, category:"kurtas", gender:"women", images:[img("women_kurta7.jpg"),   img("women_kurta8.jpg")],   sizes:["S","M","L","XL"],        colors:["Red","Yellow"],    stock:15, ratings:4.3, isFeatured:false },
  { name:"Casual Cotton Kurta",             price:1099, originalPrice:1499, discount:26, category:"kurtas", gender:"women", images:[img("women_kurta9.jpg"),   img("women_kurta10.webp")], sizes:["S","M","L","XL","XXL"],  colors:["Sky Blue","Peach"],stock:30, ratings:3.9, isFeatured:false },
  { name:"Floral Cotton Kurta",             price:1399, originalPrice:1899, discount:26, category:"kurtas", gender:"women", images:[img("women_kurta11.webp"), img("women_kurta12.jpg")],  sizes:["S","M","L","XL"],        colors:["Orange","Purple"], stock:12, ratings:4.6, isFeatured:true  },
  { name:"Premium Embroidered Kurta",       price:1599, originalPrice:2199, discount:27, category:"kurtas", gender:"women", images:[img("women_kurta13.webp"), img("women_kurta14.webp")], sizes:["S","M","L","XL"],        colors:["Maroon","Ivory"],  stock:14, ratings:4.5, isFeatured:false },
  { name:"Ethnic Block Print Kurta",        price:1199, originalPrice:1699, discount:29, category:"kurtas", gender:"women", images:[img("women_kurta15.webp"), img("womens_kurta1.avif")], sizes:["S","M","L","XL","XXL"],  colors:["Brown","Rust"],    stock:16, ratings:4.3, isFeatured:false },
  { name:"Straight Cut Kurta",              price:899,  originalPrice:1299, discount:30, category:"kurtas", gender:"women", images:[img("womens_kurta2.avif"), img("womens_kurta3.avif")], sizes:["S","M","L","XL"],        colors:["Navy","White"],    stock:22, ratings:4.1, isFeatured:false },
  { name:"A-Line Kurta",                    price:1099, originalPrice:1499, discount:26, category:"kurtas", gender:"women", images:[img("womens_kurta4.avif"), img("womens_kurta5.avif")], sizes:["S","M","L","XL","XXL"],  colors:["Coral","Grey"],    stock:20, ratings:4.2, isFeatured:false },
  { name:"Anarkali Kurta",                  price:1799, originalPrice:2499, discount:28, category:"kurtas", gender:"women", images:[img("womens_kurta6.avif"), img("womens_kurta7.avif")], sizes:["S","M","L","XL"],        colors:["Pink","Gold"],     stock:10, ratings:4.6, isFeatured:true  },
  { name:"Mirror Work Festive Kurta",       price:1599, originalPrice:2299, discount:30, category:"kurtas", gender:"women", images:[img("womens_kurta8.avif"), img("womens_kurta9.avif")], sizes:["S","M","L","XL"],        colors:["Orange","Green"],  stock:12, ratings:4.4, isFeatured:false },

  // ── WOMEN — SAREES ──
  { name:"Banarasi Silk Saree",             price:3499, originalPrice:5999, discount:41, category:"sarees", gender:"women", images:[img("women_saree1.avif"),  img("women_saree2.avif")],  sizes:["Free Size"], colors:["Red","Maroon"],    stock:10, ratings:4.7, isFeatured:true  },
  { name:"Cotton Printed Saree",            price:899,  originalPrice:1499, discount:40, category:"sarees", gender:"women", images:[img("women_saree3.avif"),  img("women_saree4.avif")],  sizes:["Free Size"], colors:["Yellow","Green"],  stock:20, ratings:4.1, isFeatured:false },
  { name:"Chiffon Party Saree",             price:1799, originalPrice:2999, discount:40, category:"sarees", gender:"women", images:[img("women_saree5.avif"),  img("women_saree6.avif")],  sizes:["Free Size"], colors:["Black","Navy"],    stock:15, ratings:4.5, isFeatured:true  },
  { name:"Kanjivaram Silk Saree",           price:4999, originalPrice:7999, discount:37, category:"sarees", gender:"women", images:[img("women_saree7.avif"),  img("women_saree8.avif")],  sizes:["Free Size"], colors:["Purple","Gold"],   stock:8,  ratings:4.8, isFeatured:true  },
  { name:"Georgette Embroidered Saree",     price:2199, originalPrice:3499, discount:37, category:"sarees", gender:"women", images:[img("women_saree9.avif"),  img("women_saree10.avif")], sizes:["Free Size"], colors:["Teal","Coral"],    stock:12, ratings:4.3, isFeatured:false },
  { name:"Daily Wear Cotton Saree",         price:699,  originalPrice:999,  discount:30, category:"sarees", gender:"women", images:[img("women_saree11.avif"), img("women_saree12.avif")], sizes:["Free Size"], colors:["Pink","Blue"],     stock:25, ratings:4.0, isFeatured:false },

  // ── WOMEN — DRESSES (women_onepiece) ──
  { name:"Cotton Casual Dress",             price:1299, originalPrice:1799, discount:27, category:"dresses", gender:"women", images:[img("women_onepiece1.avif"),  img("women_onepiece2.avif")],  sizes:["XS","S","M","L","XL"],  colors:["Pink","Blue"],    stock:22, ratings:4.3, isFeatured:true  },
  { name:"Chiffon Party Dress",             price:2199, originalPrice:2999, discount:26, category:"dresses", gender:"women", images:[img("women_onepiece3.avif"),  img("women_onepiece4.avif")],  sizes:["S","M","L"],            colors:["Black","Red"],    stock:18, ratings:4.4, isFeatured:false },
  { name:"Printed Cotton Dress",            price:1499, originalPrice:1999, discount:25, category:"dresses", gender:"women", images:[img("women_onepiece5.avif"),  img("women_onepiece6.avif")],  sizes:["S","M","L","XL"],       colors:["Stripes"],        stock:25, ratings:4.0, isFeatured:false },
  { name:"Designer Georgette Dress",        price:2799, originalPrice:3999, discount:30, category:"dresses", gender:"women", images:[img("women_onepiece7.avif"),  img("women_onepiece8.avif")],  sizes:["XS","S","M","L"],       colors:["Yellow","White"], stock:16, ratings:4.2, isFeatured:false },
  { name:"Floral Maxi Dress",               price:1499, originalPrice:2299, discount:34, category:"dresses", gender:"women", images:[img("women_onepiece9.avif"),  img("women_onepiece10.avif")], sizes:["S","M","L","XL"],       colors:["Orange","Multi"], stock:16, ratings:4.5, isFeatured:true  },
  { name:"Elegant Chiffon Dress",           price:2399, originalPrice:3199, discount:25, category:"dresses", gender:"women", images:[img("women_onepiece11.avif"), img("women_onepiece12.avif")], sizes:["S","M","L"],            colors:["Navy","Teal"],    stock:14, ratings:4.1, isFeatured:false },

  // ── WOMEN — TOPS ──
  { name:"Cotton Casual Top",               price:799,  originalPrice:1099, discount:27, category:"tops", gender:"women", images:[img("womens_top1.avif"),  img("womens_top2.avif")],  sizes:["XS","S","M","L"],       colors:["White","Black"],   stock:40, ratings:4.1, isFeatured:false },
  { name:"Chiffon Party Top",               price:1199, originalPrice:1599, discount:25, category:"tops", gender:"women", images:[img("womens_top3.avif"),  img("womens_top4.avif")],  sizes:["S","M","L","XL"],       colors:["Navy","Coral"],    stock:28, ratings:4.2, isFeatured:false },
  { name:"Printed Cotton Top",              price:899,  originalPrice:1299, discount:30, category:"tops", gender:"women", images:[img("womens_top5.avif"),  img("womens_top6.avif")],  sizes:["XS","S","M","L"],       colors:["Sky Blue","Mint"], stock:35, ratings:3.9, isFeatured:false },
  { name:"Designer Chiffon Top",            price:1399, originalPrice:1899, discount:26, category:"tops", gender:"women", images:[img("womens_top7.avif"),  img("womens_top8.avif")],  sizes:["S","M","L","XL","XXL"], colors:["White","Blue"],    stock:30, ratings:4.3, isFeatured:false },
  { name:"Elegant Linen Top",               price:1299, originalPrice:1799, discount:27, category:"tops", gender:"women", images:[img("womens_top9.avif"),  img("womens_top10.avif")], sizes:["S","M","L","XL"],       colors:["Maroon","Teal"],   stock:20, ratings:4.4, isFeatured:false },
  { name:"Floral Cotton Top",               price:999,  originalPrice:1399, discount:28, category:"tops", gender:"women", images:[img("womens_top11.avif"), img("womens_top12.avif")], sizes:["S","M","L"],            colors:["Ivory","Rust"],    stock:22, ratings:4.0, isFeatured:false },

  // ── WOMEN — LEHNGAS ──
  { name:"Bridal Lehenga Choli",            price:8999, originalPrice:14999, discount:40, category:"lehngas", gender:"women", images:[img("women_lehenga1.avif"),  img("women_lehenga2.avif")],  sizes:["S","M","L","XL"],       colors:["Red","Pink"],      stock:5,  ratings:4.8, isFeatured:true  },
  { name:"Chaniya Choli",                   price:2499, originalPrice:3999,  discount:37, category:"lehngas", gender:"women", images:[img("women_lehenga3.avif"),  img("women_lehenga4.avif")],  sizes:["S","M","L","XL"],       colors:["Yellow","Green"],  stock:12, ratings:4.6, isFeatured:true  },
  { name:"A-Line Party Lehenga",            price:3999, originalPrice:5999,  discount:33, category:"lehngas", gender:"women", images:[img("women_lehenga5.avif"),  img("women_lehenga6.avif")],  sizes:["S","M","L","XL"],       colors:["Royal Blue"],      stock:8,  ratings:4.7, isFeatured:false },
  { name:"Designer Lehenga",                price:5999, originalPrice:8999,  discount:33, category:"lehngas", gender:"women", images:[img("women_lehenga7.avif"),  img("women_lehenga8.avif")],  sizes:["S","M","L","XL"],       colors:["Maroon"],          stock:6,  ratings:4.5, isFeatured:false },
  { name:"Festive Lehenga Set",             price:4499, originalPrice:6999,  discount:35, category:"lehngas", gender:"women", images:[img("women_lehenga9.avif"),  img("women_lehenga10.avif")], sizes:["S","M","L","XL"],       colors:["Orange","Pink"],   stock:9,  ratings:4.4, isFeatured:false },
  { name:"Heavy Embroidered Lehenga",       price:6999, originalPrice:10999, discount:36, category:"lehngas", gender:"women", images:[img("women_lehenga11.avif"), img("women_lehenga12.avif")], sizes:["S","M","L","XL"],       colors:["Gold","Cream"],    stock:4,  ratings:4.9, isFeatured:true  },

  // ── WOMEN — CO-ORD SETS ──
  { name:"Printed Co-Ord Set",              price:1199, originalPrice:1899, discount:36, category:"co-ord-sets", gender:"women", images:[img("women_cordset1.avif"),  img("women_cordset2.avif")],  sizes:["XS","S","M","L","XL"],  colors:["Tropical"],       stock:20, ratings:4.3, isFeatured:true  },
  { name:"Linen Co-Ord Set",                price:1399, originalPrice:2199, discount:36, category:"co-ord-sets", gender:"women", images:[img("women_cordset3.avif"),  img("women_cordset4.avif")],  sizes:["S","M","L","XL"],       colors:["White","Beige"],  stock:18, ratings:4.4, isFeatured:false },
  { name:"Ethnic Co-Ord Set",               price:1799, originalPrice:2799, discount:35, category:"co-ord-sets", gender:"women", images:[img("women_cordset5.avif"),  img("women_cordset6.avif")],  sizes:["S","M","L","XL"],       colors:["Maroon"],         stock:14, ratings:4.5, isFeatured:false },
  { name:"Casual Co-Ord Set",               price:999,  originalPrice:1499, discount:33, category:"co-ord-sets", gender:"women", images:[img("women_cordset7.avif"),  img("women_cordset8.avif")],  sizes:["S","M","L"],            colors:["Navy","Olive"],   stock:22, ratings:4.1, isFeatured:false },
  { name:"Summer Co-Ord Set",               price:1099, originalPrice:1699, discount:35, category:"co-ord-sets", gender:"women", images:[img("women_cordset9.avif"),  img("women_cordset10.avif")], sizes:["XS","S","M","L"],       colors:["Yellow","Pink"],  stock:19, ratings:4.2, isFeatured:false },
  { name:"Party Co-Ord Set",                price:1599, originalPrice:2499, discount:35, category:"co-ord-sets", gender:"women", images:[img("women_cordset11.avif"), img("women_cordset12.avif")], sizes:["S","M","L","XL"],       colors:["Black","Gold"],   stock:12, ratings:4.6, isFeatured:true  },

  // ── WOMEN — JOGGERS ──
  { name:"Cotton Comfort Joggers",          price:799,  originalPrice:1099, discount:27, category:"joggers", gender:"women", images:[img("women_joggers1.avif"),  img("women_joggers2.avif")],  sizes:["S","M","L","XL"],       colors:["Grey","Black"],   stock:30, ratings:4.2, isFeatured:false },
  { name:"Sports Active Joggers",           price:999,  originalPrice:1499, discount:33, category:"joggers", gender:"women", images:[img("women_joggers3.avif"),  img("women_joggers4.avif")],  sizes:["XS","S","M","L","XL"],  colors:["Navy","Pink"],    stock:25, ratings:4.0, isFeatured:false },
  { name:"Fleece Joggers",                  price:1199, originalPrice:1699, discount:29, category:"joggers", gender:"women", images:[img("women_joggers5.avif"),  img("women_joggers6.avif")],  sizes:["S","M","L","XL"],       colors:["Pink","Lavender"],stock:20, ratings:4.3, isFeatured:false },
  { name:"Slim Fit Joggers",                price:899,  originalPrice:1299, discount:30, category:"joggers", gender:"women", images:[img("women_joggers7.avif"),  img("women_joggers8.avif")],  sizes:["S","M","L"],            colors:["Black","Olive"],  stock:22, ratings:4.1, isFeatured:false },
  { name:"Relaxed Cotton Joggers",          price:699,  originalPrice:999,  discount:30, category:"joggers", gender:"women", images:[img("women_joggers9.avif"),  img("women_joggers10.avif")], sizes:["S","M","L","XL","XXL"], colors:["Grey","Beige"],   stock:28, ratings:3.9, isFeatured:false },
  { name:"Premium Track Joggers",           price:1399, originalPrice:1999, discount:30, category:"joggers", gender:"women", images:[img("women_joggers11.avif"), img("women_joggers12.avif")], sizes:["S","M","L","XL"],       colors:["Charcoal"],       stock:15, ratings:4.4, isFeatured:false },

  // ── WOMEN — TRACKPANTS ──
  { name:"Active Track Pants",              price:799,  originalPrice:1199, discount:33, category:"trackpants", gender:"women", images:[img("womens_trackpant1.avif"),  img("womens_trackpant2.avif")],  sizes:["S","M","L","XL"],       colors:["Black","Navy"],   stock:28, ratings:4.1, isFeatured:false },
  { name:"Sports Track Pants",              price:999,  originalPrice:1499, discount:33, category:"trackpants", gender:"women", images:[img("womens_trackpant3.avif"),  img("womens_trackpant4.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Black","Red"],    stock:22, ratings:4.0, isFeatured:false },
  { name:"Slim Fit Track Pants",            price:1199, originalPrice:1699, discount:29, category:"trackpants", gender:"women", images:[img("womens_trackpant5.avif"),  img("womens_trackpant6.avif")],  sizes:["XS","S","M","L"],       colors:["Navy","Olive"],   stock:18, ratings:4.2, isFeatured:false },
  { name:"Cotton Track Pants",              price:699,  originalPrice:999,  discount:30, category:"trackpants", gender:"women", images:[img("womens_trackpant7.avif"),  img("womens_trackpant8.avif")],  sizes:["S","M","L","XL"],       colors:["Grey","Beige"],   stock:30, ratings:3.8, isFeatured:false },
  { name:"Running Track Pants",             price:1099, originalPrice:1599, discount:31, category:"trackpants", gender:"women", images:[img("womens_trackpant9.avif"),  img("womens_trackpant10.avif")], sizes:["S","M","L","XL"],       colors:["Black","Blue"],   stock:24, ratings:4.3, isFeatured:false },
  { name:"Premium Track Pants",             price:1499, originalPrice:2199, discount:31, category:"trackpants", gender:"women", images:[img("womens_trackpant11.avif"), img("womens_trackpant12.avif")], sizes:["S","M","L","XL"],       colors:["Charcoal"],       stock:15, ratings:4.5, isFeatured:false },

  // ── WOMEN — JUMPSUITS ──
  { name:"Casual Denim Jumpsuit",           price:1599, originalPrice:2499, discount:36, category:"jumpsuits", gender:"women", images:[img("women_jumpsuit1.avif"),  img("women_jumpsuit2.avif")],  sizes:["XS","S","M","L","XL"],  colors:["Blue","Black"],   stock:15, ratings:4.2, isFeatured:false },
  { name:"Floral Printed Jumpsuit",         price:1299, originalPrice:1999, discount:35, category:"jumpsuits", gender:"women", images:[img("women_jumpsuit3.avif"),  img("women_jumpsuit4.avif")],  sizes:["S","M","L"],            colors:["Multicolor"],     stock:18, ratings:4.3, isFeatured:false },
  { name:"Party Sequin Jumpsuit",           price:2199, originalPrice:3499, discount:37, category:"jumpsuits", gender:"women", images:[img("women_jumpsuit5.avif"),  img("women_jumpsuit6.avif")],  sizes:["XS","S","M","L"],       colors:["Gold","Black"],   stock:10, ratings:4.6, isFeatured:true  },
  { name:"Wide Leg Jumpsuit",               price:1499, originalPrice:2199, discount:31, category:"jumpsuits", gender:"women", images:[img("women_jumpsuit7.avif"),  img("women_jumpsuit8.avif")],  sizes:["S","M","L","XL"],       colors:["Olive","Rust"],   stock:14, ratings:4.1, isFeatured:false },
  { name:"Sleeveless Jumpsuit",             price:1199, originalPrice:1799, discount:33, category:"jumpsuits", gender:"women", images:[img("women_jumpsuit9.avif"),  img("women_jumpsuit10.avif")], sizes:["XS","S","M","L"],       colors:["White","Navy"],   stock:20, ratings:4.0, isFeatured:false },
  { name:"Formal Jumpsuit",                 price:1899, originalPrice:2799, discount:32, category:"jumpsuits", gender:"women", images:[img("women_jumpsuit11.avif"), img("women_jumpsuit12.avif")], sizes:["S","M","L","XL"],       colors:["Black","Grey"],   stock:12, ratings:4.4, isFeatured:false },

  // ── WOMEN — DUPPATAS ──
  { name:"Chiffon Embroidered Dupatta",     price:399,  originalPrice:699,  discount:42, category:"duppatas", gender:"women", images:[img("women_dupatta1.avif"),  img("women_dupatta2.avif")],  sizes:["Free Size"], colors:["Pink","Blue"],     stock:50, ratings:4.1, isFeatured:false },
  { name:"Bandhani Dupatta",                price:499,  originalPrice:799,  discount:37, category:"duppatas", gender:"women", images:[img("women_dupatta3.avif"),  img("women_dupatta4.avif")],  sizes:["Free Size"], colors:["Red","Yellow"],    stock:35, ratings:4.2, isFeatured:false },
  { name:"Mirror Work Dupatta",             price:799,  originalPrice:1199, discount:33, category:"duppatas", gender:"women", images:[img("women_dupatta5.avif"),  img("women_dupatta6.avif")],  sizes:["Free Size"], colors:["Orange","Magenta"],stock:20, ratings:4.4, isFeatured:false },
  { name:"Silk Dupatta",                    price:599,  originalPrice:999,  discount:40, category:"duppatas", gender:"women", images:[img("women_dupatta7.avif"),  img("women_dupatta8.avif")],  sizes:["Free Size"], colors:["Green","Gold"],    stock:30, ratings:4.0, isFeatured:false },
  { name:"Printed Cotton Dupatta",          price:299,  originalPrice:499,  discount:40, category:"duppatas", gender:"women", images:[img("women_dupatta9.avif"),  img("women_dupatta10.avif")], sizes:["Free Size"], colors:["Multi"],           stock:45, ratings:3.9, isFeatured:false },
  { name:"Embroidered Dupatta",             price:699,  originalPrice:1099, discount:36, category:"duppatas", gender:"women", images:[img("women_dupatta11.avif"), img("women_dupatta12.avif")], sizes:["Free Size"], colors:["Purple","Teal"],   stock:22, ratings:4.2, isFeatured:false },

  // ── WOMEN — SHRUGS ──
  { name:"Lace Shrug",                      price:499,  originalPrice:799,  discount:37, category:"shrugs", gender:"women", images:[img("women_shrug1.avif"),  img("women_shrug2.avif")],  sizes:["S","M","L","XL"],  colors:["White","Black"],  stock:25, ratings:4.0, isFeatured:false },
  { name:"Knit Long Shrug",                 price:799,  originalPrice:1299, discount:38, category:"shrugs", gender:"women", images:[img("women_shrug3.avif"),  img("women_shrug4.avif")],  sizes:["S","M","L"],       colors:["Grey","Beige"],   stock:20, ratings:4.2, isFeatured:false },
  { name:"Printed Shrug",                   price:599,  originalPrice:999,  discount:40, category:"shrugs", gender:"women", images:[img("women_shrug5.avif"),  img("women_shrug6.avif")],  sizes:["S","M","L","XL"],  colors:["Coral","Mint"],   stock:22, ratings:4.1, isFeatured:false },
  { name:"Denim Shrug",                     price:899,  originalPrice:1299, discount:30, category:"shrugs", gender:"women", images:[img("women_shrug7.avif"),  img("women_shrug8.avif")],  sizes:["S","M","L"],       colors:["Blue"],           stock:18, ratings:4.3, isFeatured:false },
  { name:"Floral Shrug",                    price:699,  originalPrice:1099, discount:36, category:"shrugs", gender:"women", images:[img("women_shrug9.avif"),  img("women_shrug10.avif")], sizes:["S","M","L","XL"],  colors:["Multicolor"],     stock:16, ratings:4.0, isFeatured:false },
  { name:"Boho Shrug",                      price:749,  originalPrice:1199, discount:37, category:"shrugs", gender:"women", images:[img("women_shrug11.avif"), img("women_shrug12.avif")], sizes:["S","M","L"],       colors:["Brown","Cream"],  stock:14, ratings:4.1, isFeatured:false },

  // ── WOMEN — TIGHTS ──
  { name:"Cotton Churidar Tights",          price:299,  originalPrice:499,  discount:40, category:"tights", gender:"women", images:[img("womens_tights1.avif"),  img("womens_tights2.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Black","White"],  stock:60, ratings:4.0, isFeatured:false },
  { name:"Gym Compression Tights",          price:699,  originalPrice:1099, discount:36, category:"tights", gender:"women", images:[img("womens_tights3.avif"),  img("womens_tights4.avif")],  sizes:["XS","S","M","L","XL"],  colors:["Black","Navy"],   stock:30, ratings:4.4, isFeatured:false },
  { name:"Printed Legging Tights",          price:499,  originalPrice:799,  discount:37, category:"tights", gender:"women", images:[img("womens_tights5.avif"),  img("womens_tights6.avif")],  sizes:["S","M","L","XL"],       colors:["Floral","Geo"],   stock:25, ratings:4.1, isFeatured:false },
  { name:"Thermal Tights",                  price:599,  originalPrice:899,  discount:33, category:"tights", gender:"women", images:[img("womens_tights7.avif"),  img("womens_tights8.avif")],  sizes:["S","M","L","XL"],       colors:["Black","Grey"],   stock:20, ratings:4.2, isFeatured:false },
  { name:"Sports Tights",                   price:799,  originalPrice:1199, discount:33, category:"tights", gender:"women", images:[img("womens_tights9.avif"),  img("womens_tights10.avif")], sizes:["XS","S","M","L"],       colors:["Black","Blue"],   stock:28, ratings:4.3, isFeatured:false },
  { name:"Seamless Tights",                 price:899,  originalPrice:1299, discount:30, category:"tights", gender:"women", images:[img("womens_tights11.avif"), img("womens_tights12.avif")], sizes:["S","M","L","XL"],       colors:["Nude","Black"],   stock:22, ratings:4.0, isFeatured:false },

  // ── WOMEN — TUNICS (using womens_trouser for tunics as no tunic images found) ──
  { name:"Long Cotton Tunic",               price:699,  originalPrice:1099, discount:36, category:"tunics", gender:"women", images:[img("womens_trouser1.avif"),  img("womens_trouser2.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Teal","Mustard"], stock:30, ratings:4.2, isFeatured:false },
  { name:"Embroidered Neck Tunic",          price:899,  originalPrice:1399, discount:35, category:"tunics", gender:"women", images:[img("womens_trouser3.avif"),  img("womens_trouser4.avif")],  sizes:["S","M","L","XL"],       colors:["Ivory","Rust"],   stock:22, ratings:4.3, isFeatured:false },
  { name:"Printed Tunic",                   price:799,  originalPrice:1199, discount:33, category:"tunics", gender:"women", images:[img("womens_trouser5.avif"),  img("womens_trouser6.avif")],  sizes:["S","M","L","XL"],       colors:["Pink","Blue"],    stock:25, ratings:4.0, isFeatured:false },
  { name:"Linen Tunic",                     price:999,  originalPrice:1499, discount:33, category:"tunics", gender:"women", images:[img("womens_trouser7.avif"),  img("womens_trouser8.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Natural","Grey"], stock:18, ratings:4.1, isFeatured:false },
  { name:"Floral Tunic Top",                price:849,  originalPrice:1299, discount:34, category:"tunics", gender:"women", images:[img("womens_trouser9.avif"),  img("womens_trouser10.avif")], sizes:["S","M","L"],            colors:["Multicolor"],     stock:20, ratings:4.4, isFeatured:false },
  { name:"Casual Long Tunic",               price:749,  originalPrice:1099, discount:31, category:"tunics", gender:"women", images:[img("womens_trouser11.avif"), img("womens_trouser12.avif")], sizes:["S","M","L","XL"],       colors:["Olive","Peach"],  stock:16, ratings:4.0, isFeatured:false },

  // ── MEN — KURTA ──
  { name:"Men's Cotton Kurta",              price:799,  originalPrice:1299, discount:38, category:"kurta-men", gender:"men", images:[img("mens_kurta1.avif"),  img("mens_kurta2.avif")],  sizes:["S","M","L","XL","XXL"], colors:["White","Beige"],    stock:30, ratings:4.3, isFeatured:true  },
  { name:"Men's Pathani Kurta",             price:1199, originalPrice:1899, discount:36, category:"kurta-men", gender:"men", images:[img("mens_kurta3.avif"),  img("mens_kurta4.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Cream","Blue"],     stock:22, ratings:4.4, isFeatured:false },
  { name:"Men's Printed Kurta",             price:999,  originalPrice:1499, discount:33, category:"kurta-men", gender:"men", images:[img("mens_kurta5.avif"),  img("mens_kurta6.avif")],  sizes:["S","M","L","XL"],       colors:["Blue","Maroon"],    stock:20, ratings:4.2, isFeatured:false },
  { name:"Men's Linen Kurta",               price:1099, originalPrice:1699, discount:35, category:"kurta-men", gender:"men", images:[img("mens_kurta7.avif"),  img("mens_kurta8.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Natural","Grey"],   stock:18, ratings:4.1, isFeatured:false },
  { name:"Men's Festive Kurta",             price:1799, originalPrice:2799, discount:35, category:"kurta-men", gender:"men", images:[img("mens_kurta9.avif"),  img("mens_kurta10.avif")], sizes:["S","M","L","XL","XXL"], colors:["Gold","Royal Blue"],stock:12, ratings:4.6, isFeatured:true  },
  { name:"Men's Embroidered Kurta",         price:1399, originalPrice:2199, discount:36, category:"kurta-men", gender:"men", images:[img("mens_kurta11.avif"), img("mens_kurta12.avif")], sizes:["S","M","L","XL"],       colors:["Green","Orange"],   stock:15, ratings:4.3, isFeatured:false },

  // ── MEN — SHERWANI ──
  { name:"Silk Sherwani",                   price:7999, originalPrice:12999, discount:38, category:"sherwani", gender:"men", images:[img("mens_sherwani1.avif"),  img("mens_sherwani2.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Ivory","Cream"],       stock:6,  ratings:4.8, isFeatured:true  },
  { name:"Jodhpuri Sherwani",               price:5999, originalPrice:9999,  discount:40, category:"sherwani", gender:"men", images:[img("mens_sherwani3.avif"),  img("mens_sherwani4.avif")],  sizes:["S","M","L","XL"],       colors:["Black","Navy"],        stock:8,  ratings:4.7, isFeatured:true  },
  { name:"Velvet Sherwani",                 price:9999, originalPrice:15999, discount:37, category:"sherwani", gender:"men", images:[img("mens_sherwani5.avif"),  img("mens_sherwani6.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Burgundy","Royal Blue"],stock:4, ratings:4.9, isFeatured:true  },
  { name:"Embroidered Sherwani",            price:6499, originalPrice:10999, discount:40, category:"sherwani", gender:"men", images:[img("mens_sherwani7.avif"),  img("mens_sherwani8.avif")],  sizes:["S","M","L","XL"],       colors:["Gold","Cream"],        stock:5,  ratings:4.7, isFeatured:false },
  { name:"Indo-Western Sherwani",           price:4999, originalPrice:7999,  discount:37, category:"sherwani", gender:"men", images:[img("mens_sherwani9.avif"),  img("mens_sherwani10.avif")], sizes:["S","M","L","XL","XXL"], colors:["Charcoal","Brown"],    stock:7,  ratings:4.5, isFeatured:false },
  { name:"Wedding Sherwani Set",            price:8499, originalPrice:13999, discount:39, category:"sherwani", gender:"men", images:[img("mens_sherwani11.avif"), img("mens_sherwani12.avif")], sizes:["S","M","L","XL"],       colors:["Off White","Peach"],   stock:3,  ratings:4.8, isFeatured:false },

  // ── MEN — NEHRU JACKETS ──
  { name:"Cotton Nehru Jacket",             price:1299, originalPrice:1999, discount:35, category:"nehru-jackets", gender:"men", images:[img("mens_nehrujacket1.avif"),  img("mens_nehrujacket2.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Beige","Olive"],  stock:20, ratings:4.3, isFeatured:false },
  { name:"Brocade Nehru Jacket",            price:1999, originalPrice:3199, discount:37, category:"nehru-jackets", gender:"men", images:[img("mens_nehrujacket3.avif"),  img("mens_nehrujacket4.avif")],  sizes:["S","M","L","XL"],       colors:["Gold","Maroon"],  stock:12, ratings:4.5, isFeatured:true  },
  { name:"Waistcoat Nehru Jacket",          price:1499, originalPrice:2299, discount:34, category:"nehru-jackets", gender:"men", images:[img("mens_nehrujacket5.avif"),  img("mens_nehrujacket6.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Navy","Charcoal"],stock:15, ratings:4.2, isFeatured:false },
  { name:"Silk Nehru Jacket",               price:2499, originalPrice:3999, discount:37, category:"nehru-jackets", gender:"men", images:[img("mens_nehrujacket7.avif"),  img("mens_nehrujacket8.avif")],  sizes:["S","M","L","XL"],       colors:["Black","Wine"],   stock:10, ratings:4.6, isFeatured:false },
  { name:"Festive Nehru Jacket",            price:1799, originalPrice:2799, discount:35, category:"nehru-jackets", gender:"men", images:[img("mens_nehrujacket9.avif"),  img("mens_nehrujacket10.avif")], sizes:["S","M","L","XL"],       colors:["Royal Blue"],     stock:14, ratings:4.4, isFeatured:false },
  { name:"Printed Nehru Jacket",            price:1399, originalPrice:2199, discount:36, category:"nehru-jackets", gender:"men", images:[img("mens_nehrujacket11.avif"), img("mens_nehrujacket12.avif")], sizes:["S","M","L","XL","XXL"], colors:["Green","Orange"], stock:16, ratings:4.1, isFeatured:false },

  // ── MEN — JEANS ──
  { name:"Men's Slim Fit Jeans",            price:1199, originalPrice:1999, discount:40, category:"jeans-men", gender:"men", images:[img("mens_jeans1.avif"),  img("mens_jeans2.avif")],  sizes:["28","30","32","34","36"],      colors:["Blue","Black"],   stock:35, ratings:4.2, isFeatured:true  },
  { name:"Men's Straight Fit Jeans",        price:1099, originalPrice:1799, discount:38, category:"jeans-men", gender:"men", images:[img("mens_jeans3.avif"),  img("mens_jeans4.avif")],  sizes:["28","30","32","34","36","38"], colors:["Mid Blue"],       stock:28, ratings:4.0, isFeatured:false },
  { name:"Men's Distressed Jeans",          price:1299, originalPrice:1999, discount:35, category:"jeans-men", gender:"men", images:[img("mens_jeans5.avif"),  img("mens_jeans6.avif")],  sizes:["28","30","32","34"],           colors:["Light Blue"],     stock:20, ratings:4.1, isFeatured:false },
  { name:"Men's Skinny Jeans",              price:999,  originalPrice:1599, discount:37, category:"jeans-men", gender:"men", images:[img("mens_jeans7.avif"),  img("mens_jeans8.avif")],  sizes:["28","30","32","34","36"],      colors:["Black","Grey"],   stock:25, ratings:3.9, isFeatured:false },
  { name:"Men's Regular Fit Jeans",         price:899,  originalPrice:1399, discount:35, category:"jeans-men", gender:"men", images:[img("mens_jeans9.avif"),  img("mens_jeans10.avif")], sizes:["30","32","34","36","38"],      colors:["Dark Blue"],      stock:30, ratings:4.0, isFeatured:false },
  { name:"Men's Cargo Denim Jeans",         price:1399, originalPrice:2199, discount:36, category:"jeans-men", gender:"men", images:[img("mens_jeans11.avif"), img("mens_jeans12.avif")], sizes:["28","30","32","34"],           colors:["Khaki","Olive"],  stock:18, ratings:4.3, isFeatured:false },

  // ── MEN — SHIRTS ──
  { name:"Men's Formal White Shirt",        price:899,  originalPrice:1499, discount:40, category:"shirt-men", gender:"men", images:[img("mens_shirt1.avif"),  img("mens_shirt2.avif")],  sizes:["S","M","L","XL","XXL"], colors:["White"],           stock:40, ratings:4.3, isFeatured:false },
  { name:"Men's Casual Check Shirt",        price:799,  originalPrice:1299, discount:38, category:"shirt-men", gender:"men", images:[img("mens_shirt3.avif"),  img("mens_shirt4.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Blue Check"],      stock:30, ratings:4.1, isFeatured:false },
  { name:"Men's Linen Casual Shirt",        price:1099, originalPrice:1699, discount:35, category:"shirt-men", gender:"men", images:[img("mens_shirt5.avif"),  img("mens_shirt6.avif")],  sizes:["S","M","L","XL"],       colors:["Ecru","Sky Blue"], stock:25, ratings:4.4, isFeatured:false },
  { name:"Men's Printed Shirt",             price:899,  originalPrice:1399, discount:35, category:"shirt-men", gender:"men", images:[img("mens_shirt7.avif"),  img("mens_shirt8.avif")],  sizes:["S","M","L","XL"],       colors:["Tropical"],        stock:22, ratings:4.2, isFeatured:false },
  { name:"Men's Oxford Shirt",              price:1199, originalPrice:1799, discount:33, category:"shirt-men", gender:"men", images:[img("mens_shirt9.avif"),  img("mens_shirt10.avif")], sizes:["S","M","L","XL","XXL"], colors:["Blue","Grey"],     stock:28, ratings:4.3, isFeatured:false },
  { name:"Men's Denim Shirt",               price:1299, originalPrice:1999, discount:35, category:"shirt-men", gender:"men", images:[img("mens_shirt11.avif"), img("mens_shirt12.avif")], sizes:["S","M","L","XL"],       colors:["Light Blue"],      stock:18, ratings:4.1, isFeatured:false },

  // ── MEN — T-SHIRTS ──
  { name:"Men's Plain Round Neck T-Shirt",  price:399,  originalPrice:699,  discount:42, category:"tshirt-men", gender:"men", images:[img("mens_tshirt1.avif"),  img("mens_tshirt2.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Black","White","Navy"],stock:80, ratings:4.1, isFeatured:false },
  { name:"Men's Graphic T-Shirt",           price:599,  originalPrice:999,  discount:40, category:"tshirt-men", gender:"men", images:[img("mens_tshirt3.avif"),  img("mens_tshirt4.avif")],  sizes:["S","M","L","XL"],       colors:["Black","White"],      stock:45, ratings:4.2, isFeatured:false },
  { name:"Men's Polo T-Shirt",              price:699,  originalPrice:1099, discount:36, category:"tshirt-men", gender:"men", images:[img("mens_tshirt5.avif"),  img("mens_tshirt6.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Navy","Grey"],        stock:35, ratings:4.3, isFeatured:false },
  { name:"Men's Full Sleeve T-Shirt",       price:799,  originalPrice:1199, discount:33, category:"tshirt-men", gender:"men", images:[img("mens_tshirt7.avif"),  img("mens_tshirt8.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Black","Charcoal"],   stock:30, ratings:4.0, isFeatured:false },
  { name:"Men's V-Neck T-Shirt",            price:449,  originalPrice:699,  discount:35, category:"tshirt-men", gender:"men", images:[img("mens_tshirt9.avif"),  img("mens_tshirt10.avif")], sizes:["S","M","L","XL"],       colors:["White","Grey"],       stock:40, ratings:4.1, isFeatured:false },
  { name:"Men's Striped T-Shirt",           price:549,  originalPrice:899,  discount:38, category:"tshirt-men", gender:"men", images:[img("mens_tshirt11.avif"), img("mens_tshirt12.avif")], sizes:["S","M","L","XL","XXL"], colors:["Navy/White"],         stock:32, ratings:4.2, isFeatured:false },

  // ── MEN — JOGGERS ──
  { name:"Men's Cotton Joggers",            price:799,  originalPrice:1299, discount:38, category:"joggers-men", gender:"men", images:[img("mens_joggers1.avif"),  img("mens_joggers3.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Grey","Black"],    stock:30, ratings:4.2, isFeatured:false },
  { name:"Men's Dryfit Joggers",            price:999,  originalPrice:1499, discount:33, category:"joggers-men", gender:"men", images:[img("mens_joggers4.avif"),  img("mens_joggers5.avif")],  sizes:["S","M","L","XL"],       colors:["Black","Dark Blue"],stock:22, ratings:4.3, isFeatured:false },
  { name:"Men's Sports Joggers",            price:1199, originalPrice:1799, discount:33, category:"joggers-men", gender:"men", images:[img("mens_joggers6.avif"),  img("mens_joggers7.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Navy","Olive"],    stock:18, ratings:4.1, isFeatured:false },
  { name:"Men's Track Joggers",             price:899,  originalPrice:1399, discount:35, category:"joggers-men", gender:"men", images:[img("mens_joggers8.avif"),  img("mens_joggers9.avif")],  sizes:["S","M","L","XL"],       colors:["Grey","Charcoal"], stock:25, ratings:4.0, isFeatured:false },
  { name:"Men's Fleece Joggers",            price:1099, originalPrice:1699, discount:35, category:"joggers-men", gender:"men", images:[img("mens_joggers10.avif"), img("mens_joggers11.avif")], sizes:["S","M","L","XL","XXL"], colors:["Black","Brown"],   stock:20, ratings:4.2, isFeatured:false },
  { name:"Men's Slim Fit Joggers",          price:1299, originalPrice:1999, discount:35, category:"joggers-men", gender:"men", images:[img("mens_joggers12.avif"), img("mens_joggers1.avif")],  sizes:["S","M","L","XL"],       colors:["Dark Grey"],       stock:15, ratings:4.4, isFeatured:false },

  // ── MEN — SHORTS ──
  { name:"Men's Casual Shorts",             price:499,  originalPrice:799,  discount:37, category:"shorts-men", gender:"men", images:[img("mens_short1.avif"),  img("mens_short2.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Navy","Grey"],    stock:40, ratings:4.0, isFeatured:false },
  { name:"Men's Cargo Shorts",              price:799,  originalPrice:1299, discount:38, category:"shorts-men", gender:"men", images:[img("mens_short3.avif"),  img("mens_short4.avif")],  sizes:["28","30","32","34","36"],colors:["Khaki","Olive"],  stock:25, ratings:4.2, isFeatured:false },
  { name:"Men's Gym Shorts",                price:599,  originalPrice:999,  discount:40, category:"shorts-men", gender:"men", images:[img("mens_short5.avif"),  img("mens_short6.avif")],  sizes:["S","M","L","XL"],       colors:["Black","Red"],    stock:30, ratings:4.1, isFeatured:false },
  { name:"Men's Denim Shorts",              price:899,  originalPrice:1399, discount:35, category:"shorts-men", gender:"men", images:[img("mens_short7.avif"),  img("mens_short8.avif")],  sizes:["28","30","32","34"],     colors:["Light Blue"],     stock:20, ratings:3.9, isFeatured:false },
  { name:"Men's Beach Shorts",              price:699,  originalPrice:1099, discount:36, category:"shorts-men", gender:"men", images:[img("mens_short9.avif"),  img("mens_short10.avif")], sizes:["S","M","L","XL","XXL"], colors:["Multi","Blue"],   stock:28, ratings:4.0, isFeatured:false },
  { name:"Men's Running Shorts",            price:749,  originalPrice:1199, discount:37, category:"shorts-men", gender:"men", images:[img("mens_short11.avif"), img("mens_short12.avif")], sizes:["S","M","L","XL"],       colors:["Black","Navy"],   stock:22, ratings:4.3, isFeatured:false },

  // ── MEN — JACKETS ──
  { name:"Black Leather Jacket",            price:2499, originalPrice:3999, discount:37, category:"jackets", gender:"men", images:[img("mens_jacket1.avif"),  img("mens_jacket2.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Black"],          stock:15, ratings:4.5, isFeatured:true  },
  { name:"Men's Puffer Winter Jacket",      price:2799, originalPrice:4299, discount:34, category:"jackets", gender:"men", images:[img("mens_jacket3.avif"),  img("mens_jacket4.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Black","Navy"],   stock:12, ratings:4.6, isFeatured:true  },
  { name:"Men's Hooded Casual Jacket",      price:1599, originalPrice:2499, discount:36, category:"jackets", gender:"men", images:[img("mens_jacket5.avif"),  img("mens_jacket6.avif")],  sizes:["S","M","L","XL"],       colors:["Brown","Olive"],  stock:18, ratings:4.2, isFeatured:false },
  { name:"Men's Bomber Jacket",             price:2199, originalPrice:3299, discount:33, category:"jackets", gender:"men", images:[img("mens_jacket7.avif"),  img("mens_jacket8.avif")],  sizes:["S","M","L","XL","XXL"], colors:["Green","Black"],  stock:14, ratings:4.4, isFeatured:false },
  { name:"Men's Military Jacket",           price:2399, originalPrice:3799, discount:36, category:"jackets", gender:"men", images:[img("mens_jacket9.avif"),  img("mens_jacket10.avif")], sizes:["S","M","L","XL"],       colors:["Olive","Khaki"],  stock:10, ratings:4.3, isFeatured:false },
  { name:"Men's Luxury Winter Coat",        price:3299, originalPrice:5499, discount:40, category:"jackets", gender:"men", images:[img("mens_jacket11.avif"), img("mens_jacket12.avif")], sizes:["S","M","L","XL","XXL"], colors:["Camel","Black"],  stock:8,  ratings:4.7, isFeatured:true  },

  // ── MEN — SWEATSHIRTS ──
  { name:"Men's Hooded Sweatshirt",         price:1099, originalPrice:1699, discount:35, category:"sweatshirts", gender:"men", images:[img("mens_sweatshirt1.avif"),  img("mens_sweatshirt2.avif")],  sizes:["S","M","L","XL"],       colors:["Grey","Navy"],    stock:20, ratings:4.4, isFeatured:false },
  { name:"Men's Graphic Sweatshirt",        price:999,  originalPrice:1499, discount:33, category:"sweatshirts", gender:"men", images:[img("mens_sweatshirt3.avif"),  img("mens_sweatshirt4.avif")],  sizes:["XS","S","M","L","XL"],  colors:["Off White","Black"],stock:25,ratings:4.2, isFeatured:false },
  { name:"Men's Oversized Sweatshirt",      price:1199, originalPrice:1799, discount:33, category:"sweatshirts", gender:"men", images:[img("mens_sweatshirt5.avif"),  img("mens_sweatshirt6.avif")],  sizes:["S","M","L"],            colors:["Beige","Sage"],   stock:18, ratings:4.5, isFeatured:true  },
  { name:"Men's Zip-Up Sweatshirt",         price:1299, originalPrice:1999, discount:35, category:"sweatshirts", gender:"men", images:[img("mens_sweatshirt7.avif"),  img("mens_sweatshirt8.avif")],  sizes:["S","M","L","XL"],       colors:["Navy","Olive"],   stock:16, ratings:4.1, isFeatured:false },
  { name:"Men's Fleece Pullover",           price:1499, originalPrice:2199, discount:31, category:"sweatshirts", gender:"men", images:[img("mens_sweatshirt9.avif"),  img("mens_sweatshirt10.avif")], sizes:["S","M","L","XL","XXL"], colors:["Charcoal"],       stock:14, ratings:4.3, isFeatured:false },
  { name:"Men's Crew Neck Sweatshirt",      price:899,  originalPrice:1299, discount:30, category:"sweatshirts", gender:"men", images:[img("mens_sweatshirt11.avif"), img("mens_sweatshirt12.avif")], sizes:["XS","S","M","L"],       colors:["White","Black"],  stock:22, ratings:4.0, isFeatured:false },

  // ── MEN — TROUSERS (using womens_trouser for men trousers section) ──
  { name:"Men's Formal Trousers",           price:1199, originalPrice:1899, discount:36, category:"trousers-men", gender:"men", images:[img("womens_trouser1.avif"),  img("womens_trouser2.avif")],  sizes:["28","30","32","34","36","38"], colors:["Black","Navy"],  stock:28, ratings:4.3, isFeatured:false },
  { name:"Men's Chino Trousers",            price:999,  originalPrice:1599, discount:37, category:"trousers-men", gender:"men", images:[img("womens_trouser3.avif"),  img("womens_trouser4.avif")],  sizes:["28","30","32","34","36"],      colors:["Beige","Olive"], stock:25, ratings:4.1, isFeatured:false },
  { name:"Men's Slim Fit Trousers",         price:1099, originalPrice:1699, discount:35, category:"trousers-men", gender:"men", images:[img("womens_trouser5.avif"),  img("womens_trouser6.avif")],  sizes:["28","30","32","34","36"],      colors:["Charcoal"],      stock:22, ratings:4.2, isFeatured:false },
  { name:"Men's Casual Trousers",           price:899,  originalPrice:1399, discount:35, category:"trousers-men", gender:"men", images:[img("womens_trouser7.avif"),  img("womens_trouser8.avif")],  sizes:["28","30","32","34"],           colors:["Khaki","Brown"], stock:18, ratings:4.0, isFeatured:false },
  { name:"Men's Linen Trousers",            price:1299, originalPrice:1999, discount:35, category:"trousers-men", gender:"men", images:[img("womens_trouser9.avif"),  img("womens_trouser10.avif")], sizes:["28","30","32","34","36"],      colors:["White","Beige"], stock:16, ratings:4.4, isFeatured:false },
  { name:"Men's Cargo Trousers",            price:1199, originalPrice:1799, discount:33, category:"trousers-men", gender:"men", images:[img("womens_trouser11.avif"), img("womens_trouser12.avif")], sizes:["28","30","32","34"],           colors:["Olive","Khaki"], stock:20, ratings:4.1, isFeatured:false },

  // ── KIDS — BOYS SHIRTS ──
  { name:"Boys Casual Check Shirt",         price:499,  originalPrice:799,  discount:37, category:"kids-boys-shirts", gender:"kids", images:[img("boys_shirt1.avif"),  img("boys_shirt2.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["Blue Check","Red Check"],stock:30, ratings:4.2, isFeatured:false },
  { name:"Boys Formal White Shirt",         price:399,  originalPrice:699,  discount:42, category:"kids-boys-shirts", gender:"kids", images:[img("boys_shirt3.avif"),  img("boys_shirt4.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["White"],          stock:40, ratings:4.0, isFeatured:false },
  { name:"Boys Printed Shirt",              price:449,  originalPrice:699,  discount:35, category:"kids-boys-shirts", gender:"kids", images:[img("boys_shirt5.avif"),  img("boys_shirt6.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y"],        colors:["Multicolor"],     stock:28, ratings:4.1, isFeatured:false },
  { name:"Boys Linen Shirt",                price:549,  originalPrice:899,  discount:38, category:"kids-boys-shirts", gender:"kids", images:[img("boys_shirt7.avif"),  img("boys_shirt8.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Sky Blue","White"],stock:22, ratings:4.2, isFeatured:false },
  { name:"Boys Denim Shirt",                price:599,  originalPrice:999,  discount:40, category:"kids-boys-shirts", gender:"kids", images:[img("boys_shirt9.avif"),  img("boys_shirt10.avif")], sizes:["4-5Y","5-6Y","6-7Y","7-8Y"],        colors:["Light Blue"],     stock:18, ratings:4.0, isFeatured:false },
  { name:"Boys Party Shirt",                price:699,  originalPrice:1099, discount:36, category:"kids-boys-shirts", gender:"kids", images:[img("boys_shirt11.avif"), img("boys_shirt12.avif")], sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["White","Cream"],  stock:15, ratings:4.3, isFeatured:false },

  // ── KIDS — BOYS T-SHIRTS ──
  { name:"Boys Graphic T-Shirt",            price:299,  originalPrice:499,  discount:40, category:"kids-boys-tshirts", gender:"kids", images:[img("boys_tshirt1.avif"),  img("boys_tshirt2.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["Red","Blue"],     stock:50, ratings:4.3, isFeatured:false },
  { name:"Boys Polo T-Shirt",               price:349,  originalPrice:599,  discount:41, category:"kids-boys-tshirts", gender:"kids", images:[img("boys_tshirt3.avif"),  img("boys_tshirt4.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Navy","Green"],   stock:35, ratings:4.1, isFeatured:false },
  { name:"Boys Striped T-Shirt",            price:299,  originalPrice:499,  discount:40, category:"kids-boys-tshirts", gender:"kids", images:[img("boys_tshirt5.avif"),  img("boys_tshirt6.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y"],        colors:["Navy/White"],     stock:40, ratings:4.0, isFeatured:false },
  { name:"Boys Plain Round Neck Tee",       price:249,  originalPrice:399,  discount:37, category:"kids-boys-tshirts", gender:"kids", images:[img("boys_tshirt7.avif"),  img("boys_tshirt8.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["Black","White"],  stock:60, ratings:3.9, isFeatured:false },
  { name:"Boys Printed Tee",                price:349,  originalPrice:549,  discount:36, category:"kids-boys-tshirts", gender:"kids", images:[img("boys_tshirt9.avif"),  img("boys_tshirt10.avif")], sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Yellow","Orange"],stock:45, ratings:4.2, isFeatured:false },
  { name:"Boys Sports T-Shirt",             price:399,  originalPrice:649,  discount:38, category:"kids-boys-tshirts", gender:"kids", images:[img("boys_tshirt11.avif"), img("boys_tshirt12.avif")], sizes:["4-5Y","5-6Y","6-7Y","7-8Y"],        colors:["Blue","Red"],     stock:30, ratings:4.1, isFeatured:false },

  // ── KIDS — BOYS SWEATSHIRTS ──
  { name:"Boys Hoodie Sweatshirt",          price:699,  originalPrice:1099, discount:36, category:"kids-boys-sweatshirts", gender:"kids", images:[img("boys_sweatshirt1.avif"),  img("boys_sweatshirt2.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Grey","Blue"],  stock:25, ratings:4.4, isFeatured:false },
  { name:"Boys Zip-Up Sweatshirt",          price:799,  originalPrice:1199, discount:33, category:"kids-boys-sweatshirts", gender:"kids", images:[img("boys_sweatshirt3.avif"),  img("boys_sweatshirt4.avif")],  sizes:["4-5Y","5-6Y","6-7Y","7-8Y"],        colors:["Navy","Black"], stock:20, ratings:4.2, isFeatured:false },
  { name:"Boys Graphic Sweatshirt",         price:649,  originalPrice:999,  discount:35, category:"kids-boys-sweatshirts", gender:"kids", images:[img("boys_sweatshirt6.avif"),  img("boys_sweatshirt7.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y"],        colors:["Red","Green"],  stock:22, ratings:4.1, isFeatured:false },
  { name:"Boys Fleece Sweatshirt",          price:899,  originalPrice:1399, discount:35, category:"kids-boys-sweatshirts", gender:"kids", images:[img("boys_sweatshirt9.avif"),  img("boys_sweatshirt10.avif")], sizes:["4-5Y","5-6Y","6-7Y","7-8Y"],        colors:["Grey","Olive"], stock:18, ratings:4.3, isFeatured:false },
  { name:"Boys Winter Sweatshirt",          price:999,  originalPrice:1499, discount:33, category:"kids-boys-sweatshirts", gender:"kids", images:[img("boys_sweatshirt11.avif"), img("boys_sweatshirt12.avif")], sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Navy","Maroon"],stock:16, ratings:4.2, isFeatured:false },

  // ── KIDS — BOYS NIGHTWEAR ──
  { name:"Boys Night Suit Set",             price:499,  originalPrice:799,  discount:37, category:"kids-boys-nightwear", gender:"kids", images:[img("boys_nightwear1.avif"),  img("boys_nightwear2.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["Blue","Green"],   stock:30, ratings:4.3, isFeatured:false },
  { name:"Boys Pyjama Set",                 price:399,  originalPrice:699,  discount:42, category:"kids-boys-nightwear", gender:"kids", images:[img("boys_nightwear3.avif"),  img("boys_nightwear4.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y"],        colors:["Red Check"],      stock:35, ratings:4.1, isFeatured:false },
  { name:"Boys Cartoon Night Suit",         price:549,  originalPrice:899,  discount:38, category:"kids-boys-nightwear", gender:"kids", images:[img("boys_nightwear5.avif"),  img("boys_nightwear6.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Blue","Yellow"],  stock:28, ratings:4.2, isFeatured:false },
  { name:"Boys Soft Cotton Pyjamas",        price:449,  originalPrice:699,  discount:35, category:"kids-boys-nightwear", gender:"kids", images:[img("boys_nightwear7.avif"),  img("boys_nightwear8.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y"],        colors:["Grey","White"],   stock:32, ratings:4.0, isFeatured:false },
  { name:"Boys Winter Night Suit",          price:699,  originalPrice:1099, discount:36, category:"kids-boys-nightwear", gender:"kids", images:[img("boys_nightwear9.avif"),  img("boys_nightwear10.avif")], sizes:["4-5Y","5-6Y","6-7Y","7-8Y"],        colors:["Navy","Dark Red"],stock:20, ratings:4.3, isFeatured:false },
  { name:"Boys Printed Pyjama Set",         price:499,  originalPrice:799,  discount:37, category:"kids-boys-nightwear", gender:"kids", images:[img("boys_nightwear11.avif"), img("boys_nightwear12.avif")], sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["Multicolor"],     stock:25, ratings:4.1, isFeatured:false },

  // ── KIDS — BOYS JACKETS ──
  { name:"Boys Puffer Jacket",              price:1199, originalPrice:1899, discount:36, category:"kids-boys-jackets", gender:"kids", images:[img("kids_jacket1.avif"),  img("kids_jacket2.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Blue","Black"],  stock:18, ratings:4.5, isFeatured:false },
  { name:"Boys Denim Jacket",               price:999,  originalPrice:1599, discount:37, category:"kids-boys-jackets", gender:"kids", images:[img("kids_jacket3.avif"),  img("kids_jacket4.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Light Blue"],    stock:15, ratings:4.3, isFeatured:false },
  { name:"Boys Hooded Jacket",              price:1099, originalPrice:1699, discount:35, category:"kids-boys-jackets", gender:"kids", images:[img("kids_jacket5.avif"),  img("kids_jacket6.avif")],  sizes:["4-5Y","5-6Y","6-7Y","7-8Y"],        colors:["Red","Navy"],    stock:14, ratings:4.2, isFeatured:false },
  { name:"Boys Fleece Jacket",              price:899,  originalPrice:1399, discount:35, category:"kids-boys-jackets", gender:"kids", images:[img("kids_jacket7.avif"),  img("kids_jacket8.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y"],        colors:["Grey","Green"],  stock:16, ratings:4.1, isFeatured:false },
  { name:"Boys Windcheater Jacket",         price:799,  originalPrice:1299, discount:38, category:"kids-boys-jackets", gender:"kids", images:[img("kids_jacket9.avif"),  img("kids_jacket10.avif")], sizes:["4-5Y","5-6Y","6-7Y","7-8Y"],        colors:["Blue","Yellow"], stock:20, ratings:4.0, isFeatured:false },
  { name:"Boys Winter Coat",                price:1499, originalPrice:2299, discount:34, category:"kids-boys-jackets", gender:"kids", images:[img("kids_jacket11.avif"), img("kids_jacket12.avif")], sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Black","Brown"], stock:10, ratings:4.4, isFeatured:false },

  // ── KIDS — GIRLS DRESSES ──
  { name:"Girls Floral Frock",              price:599,  originalPrice:999,  discount:40, category:"kids-girls-dresses", gender:"kids", images:[img("kids_dress1.avif"),  img("kids_dress2.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["Pink","Yellow"],  stock:30, ratings:4.4, isFeatured:false },
  { name:"Girls Tutu Dress",                price:799,  originalPrice:1299, discount:38, category:"kids-girls-dresses", gender:"kids", images:[img("kids_dress3.avif"),  img("kids_dress4.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y"],        colors:["Pink","Purple"],  stock:22, ratings:4.5, isFeatured:false },
  { name:"Girls Casual Dress",              price:499,  originalPrice:799,  discount:37, category:"kids-girls-dresses", gender:"kids", images:[img("kids_dress5.avif"),  img("kids_dress6.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["Blue","Red"],     stock:35, ratings:4.2, isFeatured:false },
  { name:"Girls Party Frock",               price:999,  originalPrice:1599, discount:37, category:"kids-girls-dresses", gender:"kids", images:[img("kids_dress7.avif"),  img("kids_dress8.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y"],        colors:["Gold","Pink"],    stock:18, ratings:4.6, isFeatured:true  },
  { name:"Girls Summer Dress",              price:699,  originalPrice:1099, discount:36, category:"kids-girls-dresses", gender:"kids", images:[img("kids_dress9.avif"),  img("kids_dress10.avif")], sizes:["2-3Y","3-4Y","4-5Y","5-6Y"],        colors:["Yellow","White"], stock:25, ratings:4.3, isFeatured:false },
  { name:"Girls Printed Dress",             price:549,  originalPrice:899,  discount:38, category:"kids-girls-dresses", gender:"kids", images:[img("kids_dress11.avif"), img("kids_dress12.avif")], sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["Multicolor"],     stock:28, ratings:4.1, isFeatured:false },

  // ── KIDS — GIRLS SWEATSHIRTS ──
  { name:"Girls Hoodie Sweatshirt",         price:699,  originalPrice:1099, discount:36, category:"kids-girls-sweatshirts", gender:"kids", images:[img("girl_sweatshirt1.avif"),  img("girl_sweatshirt2.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Pink","Lavender"],stock:25, ratings:4.5, isFeatured:false },
  { name:"Girls Printed Sweatshirt",        price:599,  originalPrice:999,  discount:40, category:"kids-girls-sweatshirts", gender:"kids", images:[img("girl_sweatshirt3.avif"),  img("girl_sweatshirt4.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y"],        colors:["Pink","Mint"],    stock:28, ratings:4.3, isFeatured:false },
  { name:"Girls Unicorn Sweatshirt",        price:749,  originalPrice:1199, discount:37, category:"kids-girls-sweatshirts", gender:"kids", images:[img("girl_sweatshirt5.avif"),  img("girl_sweatshirt6.avif")],  sizes:["4-5Y","5-6Y","6-7Y","7-8Y"],        colors:["Purple","White"], stock:20, ratings:4.4, isFeatured:false },
  { name:"Girls Zip-Up Sweatshirt",         price:799,  originalPrice:1299, discount:38, category:"kids-girls-sweatshirts", gender:"kids", images:[img("girl_sweatshirt7.avif"),  img("girl_sweatshirt8.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y"],        colors:["Navy","Red"],     stock:18, ratings:4.2, isFeatured:false },
  { name:"Girls Fleece Sweatshirt",         price:899,  originalPrice:1399, discount:35, category:"kids-girls-sweatshirts", gender:"kids", images:[img("girl_sweatshirt9.avif"),  img("girl_sweatshirt10.avif")], sizes:["4-5Y","5-6Y","6-7Y","7-8Y"],        colors:["Pink","Grey"],    stock:15, ratings:4.3, isFeatured:false },
  { name:"Girls Glitter Sweatshirt",        price:849,  originalPrice:1299, discount:34, category:"kids-girls-sweatshirts", gender:"kids", images:[img("girl_sweatshirt11.avif"), img("girl_sweatshirt12.avif")], sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Gold","Pink"],    stock:12, ratings:4.6, isFeatured:false },

  // ── KIDS — GIRLS NIGHTWEAR ──
  { name:"Girls Night Suit",                price:499,  originalPrice:799,  discount:37, category:"kids-girls-nightwear", gender:"kids", images:[img("kids_nightwear1.avif"),  img("kids_nightwear2.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["Pink","Lilac"],   stock:30, ratings:4.4, isFeatured:false },
  { name:"Girls Pyjama Set",                price:399,  originalPrice:699,  discount:42, category:"kids-girls-nightwear", gender:"kids", images:[img("kids_nightwear3.avif"),  img("kids_nightwear4.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y"],        colors:["Pink Floral"],    stock:35, ratings:4.2, isFeatured:false },
  { name:"Girls Princess Night Suit",       price:599,  originalPrice:999,  discount:40, category:"kids-girls-nightwear", gender:"kids", images:[img("kids_nightwear5.avif"),  img("kids_nightwear6.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Purple","Pink"],  stock:25, ratings:4.5, isFeatured:false },
  { name:"Girls Soft Cotton Pyjamas",       price:449,  originalPrice:699,  discount:35, category:"kids-girls-nightwear", gender:"kids", images:[img("kids_nightwear7.avif"),  img("kids_nightwear8.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y"],        colors:["White","Yellow"], stock:28, ratings:4.1, isFeatured:false },
  { name:"Girls Winter Night Suit",         price:699,  originalPrice:1099, discount:36, category:"kids-girls-nightwear", gender:"kids", images:[img("kids_nightwear9.avif"),  img("kids_nightwear10.avif")], sizes:["4-5Y","5-6Y","6-7Y","7-8Y"],        colors:["Navy","Maroon"],  stock:20, ratings:4.3, isFeatured:false },
  { name:"Girls Satin Pyjama Set",          price:549,  originalPrice:899,  discount:38, category:"kids-girls-nightwear", gender:"kids", images:[img("kids_nightwear11.avif"), img("kids_nightwear12.avif")], sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Pink","Lavender"],stock:22, ratings:4.0, isFeatured:false },

  // ── KIDS — GIRLS PARTYWEAR ──
  { name:"Girls Party Gown",                price:1299, originalPrice:1999, discount:35, category:"kids-girls-partywear", gender:"kids", images:[img("kids_partywear1.avif"),  img("kids_partywear2.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["Pink","Blue","Gold"],stock:15, ratings:4.6, isFeatured:true  },
  { name:"Girls Princess Dress",            price:999,  originalPrice:1599, discount:37, category:"kids-girls-partywear", gender:"kids", images:[img("kids_partywear3.avif"),  img("kids_partywear4.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y"],        colors:["Purple","Pink"],  stock:18, ratings:4.7, isFeatured:true  },
  { name:"Girls Sequin Party Dress",        price:1199, originalPrice:1899, discount:36, category:"kids-girls-partywear", gender:"kids", images:[img("kids_partywear5.avif"),  img("kids_partywear6.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Gold","Silver"],  stock:12, ratings:4.5, isFeatured:false },
  { name:"Girls Floral Party Frock",        price:899,  originalPrice:1399, discount:35, category:"kids-girls-partywear", gender:"kids", images:[img("kids_partywear7.avif"),  img("kids_partywear8.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y"],        colors:["Yellow","Pink"],  stock:20, ratings:4.4, isFeatured:false },
  { name:"Girls Tulle Party Dress",         price:1499, originalPrice:2299, discount:34, category:"kids-girls-partywear", gender:"kids", images:[img("kids_partywear9.avif"),  img("kids_partywear10.avif")], sizes:["3-4Y","4-5Y","5-6Y","6-7Y"],        colors:["White","Blue"],   stock:10, ratings:4.8, isFeatured:true  },
  { name:"Girls Birthday Dress",            price:1099, originalPrice:1699, discount:35, category:"kids-girls-partywear", gender:"kids", images:[img("kids_partywear11.avif"), img("kids_partywear12.avif")], sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"], colors:["Pink","Red"],     stock:14, ratings:4.6, isFeatured:false },

  // ── KIDS — SAREES ──
  { name:"Girls Kids Silk Saree",           price:899,  originalPrice:1499, discount:40, category:"kids-sarees", gender:"kids", images:[img("kids_saree1.avif"),  img("kids_saree2.avif")],  sizes:["Free Size"], colors:["Red","Pink"],     stock:15, ratings:4.4, isFeatured:false },
  { name:"Girls Embroidered Saree",         price:1199, originalPrice:1899, discount:36, category:"kids-sarees", gender:"kids", images:[img("kids_saree3.avif"),  img("kids_saree4.avif")],  sizes:["Free Size"], colors:["Yellow","Blue"],  stock:10, ratings:4.3, isFeatured:false },
  { name:"Girls Cotton Saree",              price:799,  originalPrice:1299, discount:38, category:"kids-sarees", gender:"kids", images:[img("kids_saree5.avif"),  img("kids_saree6.avif")],  sizes:["Free Size"], colors:["Green","Orange"], stock:12, ratings:4.1, isFeatured:false },
  { name:"Girls Fancy Saree",               price:1499, originalPrice:2199, discount:31, category:"kids-sarees", gender:"kids", images:[img("kids_saree7.avif"),  img("kids_saree8.avif")],  sizes:["Free Size"], colors:["Purple","Gold"],  stock:8,  ratings:4.5, isFeatured:false },
  { name:"Girls Silk Saree Set",            price:1299, originalPrice:1999, discount:34, category:"kids-sarees", gender:"kids", images:[img("kids_saree9.avif"),  img("kids_saree10.avif")], sizes:["Free Size"], colors:["Maroon","Teal"],  stock:9,  ratings:4.2, isFeatured:false },
  { name:"Girls Designer Saree",            price:1799, originalPrice:2799, discount:35, category:"kids-sarees", gender:"kids", images:[img("kids_saree11.avif"), img("kids_saree12.avif")], sizes:["Free Size"], colors:["Blue","Pink"],    stock:6,  ratings:4.6, isFeatured:false },

  // ── KIDS — ETHNIC WEAR ──
  { name:"Kids Kurta Pyjama Set",           price:799,  originalPrice:1299, discount:38, category:"kids-ethnic", gender:"kids", images:[img("kids_ethnic1.avif"),  img("kids_ethnic2.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"], colors:["Yellow","Green"],stock:25, ratings:4.4, isFeatured:true  },
  { name:"Girls Lehenga Choli",             price:1299, originalPrice:1999, discount:35, category:"kids-ethnic", gender:"kids", images:[img("kids_ethnic3.avif"),  img("kids_ethnic4.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"],         colors:["Orange","Pink"],  stock:18, ratings:4.6, isFeatured:true  },
  { name:"Boys Sherwani Set",               price:1999, originalPrice:2999, discount:33, category:"kids-ethnic", gender:"kids", images:[img("kids_ethnic5.avif"),  img("kids_ethnic6.avif")],  sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"],         colors:["Cream","Gold"],   stock:10, ratings:4.7, isFeatured:true  },
  { name:"Girls Anarkali Suit",             price:1099, originalPrice:1699, discount:35, category:"kids-ethnic", gender:"kids", images:[img("kids_ethnic7.avif"),  img("kids_ethnic8.avif")],  sizes:["2-3Y","3-4Y","4-5Y","5-6Y"],                colors:["Red","Purple"],   stock:16, ratings:4.5, isFeatured:false },
  { name:"Kids Dhoti Kurta Set",            price:899,  originalPrice:1399, discount:35, category:"kids-ethnic", gender:"kids", images:[img("kids_ethnic9.avif"),  img("kids_ethnic10.avif")], sizes:["3-4Y","4-5Y","5-6Y","6-7Y","7-8Y"],         colors:["White","Yellow"], stock:20, ratings:4.3, isFeatured:false },
  { name:"Girls Sharara Set",               price:1199, originalPrice:1799, discount:33, category:"kids-ethnic", gender:"kids", images:[img("kids_ethnic11.avif"), img("kids_ethnic12.avif")], sizes:["2-3Y","3-4Y","4-5Y","5-6Y","6-7Y"],         colors:["Pink","Blue"],    stock:14, ratings:4.4, isFeatured:false },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ Connected to MongoDB");
    await Product.deleteMany({});
    console.log("🗑️  Cleared existing products");
    await Product.insertMany(products);
    console.log(`🌱 Seeded ${products.length} products with updated image names`);
    mongoose.disconnect();
    console.log("🔌 Done!");
  } catch (err) {
    console.error("❌ Seed error:", err.message);
    process.exit(1);
  }
};

seedDB();
